Swagger
go-devs-ua/octagon pull request #3
Opened 2022-09-28 17:19 UTC by Anton-Hudz

Feat: changed file openapi.yml(docs/openapi.yml)

2022-09-28 17:31 UTC, Rusli4k commented on docs/openapi.yml
> +      description: This endpoint for create a new user to Octagon. Request consists of user id, user first name, user last name, user password and created AT. Response may be consist of status code a
Does request has to consist ID ? And created at?

2022-09-28 17:31 UTC, Rusli4k commented on docs/openapi.yml
> +          description: must be @ and must be unique
not "must be" but "must contains" ...'@'

2022-09-28 17:56 UTC, Anton-Hudz commented on docs/openapi.yml
> +      description: This endpoint for create a new user to Octagon. Request consists of user id, user first name, user last name, user password and created AT. Response may be consist of status code a
Nope, because we don't expect these fields from user (in API)

2022-09-28 17:57 UTC, Anton-Hudz commented on docs/openapi.yml
> +          description: must be @ and must be unique
I know, however
![image](https://user-images.githubusercontent.com/98592774/192854863-28fd1e59-2534-43c5-b3b4-366e1aa9210f.png)

2022-09-28 18:25 UTC, Rusli4k commented on docs/openapi.yml
> +      description: This endpoint for create a new user to Octagon. Request consists of user id, user first name, user last name, user password and created AT. Response may be consist of status code a
So why does the description consisnts those fields as needed?

2022-09-28 18:47 UTC, Anton-Hudz commented on docs/openapi.yml
> +      description: This endpoint for create a new user to Octagon. Request consists of user id, user first name, user last name, user password and created AT. Response may be consist of status code a
In our case we do not need to get ID and CreatedAT from the user. We will generate this data on the BackEnd side

2022-09-28 20:05 UTC, andstepko commented on docs/openapi.yml
> +          description: must be @ and must be unique
Я би сказав, що просто вимоги на скору руку писали

2022-09-28 20:05 UTC, andstepko commented on docs/openapi.yml
> +        "422":
Зазвичай якщо невалідний запит прийшов - повертають 400. 422 - то вже для якихось окремих нестандартних випадків.

2022-09-28 20:07 UTC, andstepko commented on docs/openapi.yml
> +      description: This endpoint for create a new user to Octagon. Request consists of user id, user first name, user last name, user password and created AT. Response may be consist of status code a
Ну то треба тоді прибрати напис, що це аргументи мають бути в реквесті 🤔

2022-09-28 20:12 UTC, andstepko commented on docs/openapi.yml
> +        description: Created user object
"Created" - це "створени". У запиті передають не вже створеного юзера, а того який ще не існує

2022-09-28 20:18 UTC, andstepko commented on docs/openapi.yml
> +          type: string
У всіх цих схем по суті однакова структура, я не певен, що є сенс мати окрему схему під кожен статус-код.

2022-09-29 10:38 UTC, Anton-Hudz commented on docs/openapi.yml
> +        description: Created user object
Получается примерно так: "Passes user data to create it"?

2022-09-29 10:38 UTC, Anton-Hudz commented on docs/openapi.yml
> +          description: must be @ and must be unique
Ок

2022-09-29 10:39 UTC, Anton-Hudz commented on docs/openapi.yml
> +      description: This endpoint for create a new user to Octagon. Request consists of user id, user first name, user last name, user password and created AT. Response may be consist of status code a
Ок

2022-09-29 11:05 UTC, vpakhuchyi commented on docs/openapi.yml
> +          type: string
Я б оці схеми 400, 500 обʼєднав би в одну - Erorr.

Проте, я б створив ще схеми для різних респонсів - 200, 400.
Таким чином, респонси виглядали б так:
```     
     responses:
        '201': { $ref: '#/components/responses/Create' }    
        '400': { $ref: '#/components/responses/BadRequest' }
         .....
```

Ті схеми мають посилатись на схему Error.
Тобто, components/responses/BadRequest буде мати дескріпшн та включати в себе Error схему.

2022-09-29 11:05 UTC, vpakhuchyi commented on docs/openapi.yml
> +          type: string
Якщо не знайдеш, як то праивльно зробити - пиінгу, допоможу.

2022-09-29 11:06 UTC, vpakhuchyi commented on docs/openapi.yml
> +  - url: http://localhost:8080/users
Думаю, що users - тут зайве.  У нас єдиний сервер поки що.

2022-09-29 11:09 UTC, vpakhuchyi commented on docs/openapi.yml
> +          description: must be @ and must be unique
Маю ще субʼєктивну пораду - намагатись писати в один рядок, якщо це можливо.
Це зробить файл меншим і буде легше по ньому рухатись та читати.
Тут дозволено використовувати {}, в яких можуть бути key-value пари.

2022-09-29 11:10 UTC, Anton-Hudz commented on docs/openapi.yml
> +        "422":
Убираю 422

2022-09-29 11:18 UTC, andstepko commented on docs/openapi.yml
> +        description: Created user object
"Passes user data to create User"
А то можна буде подумати, що create data

2022-09-29 11:20 UTC, andstepko commented on docs/openapi.yml
> +          type: string
@vpakhuchyi а чи потрібні взагалі схеми BadRequest, Conflict etc? Чом би одразу не посилатись з усіх помилок на схему `Error`?

2022-09-29 11:47 UTC, Anton-Hudz commented on docs/openapi.yml
> +        description: Created user object
Ok

2022-09-29 11:50 UTC, Anton-Hudz commented on docs/openapi.yml
> +  - url: http://localhost:8080/users
Понял, исправлю

2022-09-29 12:29 UTC, vpakhuchyi commented on docs/openapi.yml
> +          type: string
Коли бачиш різні схеми - значно легше читати.
Глянь на приклад вище. Тобі вже зрозуміло, що то буде +-.
А якщко там буде Error - менш змістовно і теба перевірити, який саме.

2022-09-29 13:46 UTC, Anton-Hudz commented on docs/openapi.yml
> +          type: string
Добавил респонзы и сделал одну схему на ошибки

2022-09-29 13:55 UTC, Anton-Hudz commented on docs/openapi.yml
> +          description: must be @ and must be unique
Откорректировал

2022-09-29 14:06 UTC, vpakhuchyi commented on docs/openapi.yml
> +  - url: http://localhost:8080/users
Сорі, що не був точним першого разу - слеш нам теж не потрібен
Треба залишити лише `http://localhost:8080`

2022-09-29 14:12 UTC, Anton-Hudz commented on docs/openapi.yml
> +  - url: http://localhost:8080/users
минутку))

2022-09-29 14:38 UTC, vpakhuchyi approved these changes

2022-09-29 14:42 UTC, vpakhuchyi requested changes
Wrong branch name.
Should be feat/add-swagger-doc

2022-09-30 13:29 UTC, closed without merging